FROM golang:1.22.1 AS builder

WORKDIR /app/server

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /server ./cmd/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /server /app/server

CMD ["/app/server"]
